config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get 'home/about'=>'homes#about'
  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    # フォロー・フォロワー
    get 'relationships/followeds' => 'relationships#followeds', as: 'followeds'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  
    get "date_count" => "users#date_count"
  end
  resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
    
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :comment,presence:true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = @book.id
    comment.save
    @book_comment = BookComment.new
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
    @book_comment = BookComment.new
  end
  
  private
  
  def book_comment_params
  params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_commentcount.html.erb
<%= "コメント数:#{book.book_comments.count}"%>

app/views/book_comments/_commentindex.html.erb
<table>
  <tbody>
    <% @book.book_comments.each do |comment| %>
      <tr>
        <td>
          <%= link_to(comment.user) do %>
            <%= image_tag comment.user.get_profile_image, size:'50x50' %><br>
            <%= comment.user.name %>
          <% end %>
        </td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Destroy', book_book_comment_path(comment.book,comment), method: :delete, remote: true, class: "btn btn-sm btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_with model: [@book,@book_comment],local: false do |f|%>
  <div>
    <%= f.label :comment %>
  </div>
  <div>
    <%= f.text_area :comment %>
  </div>
  <div>
    <%= f.submit "送信" %>
  </div>
<% end %>

app/views/book_comments/create.js.erb
$('#comment<%= @book.id %>').html("<%= escape_javascript(render partial: 'book_comments/commentindex', locals: {book: @book,book_comment: @book_comment}) %>");
$('#count<%= @book.id %>').html("<%= escape_javascript(render partial: 'book_comments/commentcount', locals: {book: @book}) %>");

app/views/book_comments/destroy.js.erb
$('#comment<%= @book.id %>').html("<%= escape_javascript(render partial: 'book_comments/commentindex', locals: {book: @book,book_comment: @book_comment}) %>");
$('#count<%= @book.id %>').html("<%= escape_javascript(render partial: 'book_comments/commentcount', locals: {book: @book}) %>");