config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get 'home/about'=>'homes#about'
  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    # フォロー・フォロワー
    get 'relationships/followeds' => 'relationships#followeds', as: 'followeds'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  
    get "date_count" => "users#date_count"
  end
  resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
    
  end
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship",foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, through: :relationships, source: :followed
  has_many :re_relationships, class_name: "Relationship",foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :re_relationships, source: :follower
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def followed?(user)
    followeds.include?(user)
  end
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  # 検索機能
  def self.looks(search,ward)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{ward}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{ward}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{ward}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{ward}%")
    else
      @user = User.all
    end
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    
    @today_book = @books.created_today
    @oneday_ago_book = @books.created_oneday_ago
    @twoday_ago_book = @books.created_twoday_ago
    @threeday_ago_book = @books.created_threeday_ago
    @fourday_ago_book = @books.created_fourday_ago
    @fiveday_ago_book = @books.created_fiveday_ago
    @sixday_ago_book = @books.created_sixday_ago
    @week_book = @books.created_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def date_count
    @user = User.find(params[:user_id])
     if params[:created_at].present?
        @date_book = @user.books.where(created_at: params[:created_at].to_date.all_day)
     end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_books_data.html.erb
    <h3>Created</h3>
    <table class='table table-hover table-inverse'>
      <tr>
        <thead>
          <th>昨日</th>
          <th>今日</th>
          <th>前日比</th>
        </thead>
      </tr>
      <tr>
        <tbody>
          <td><%= @oneday_ago_book.count %></td>
          <td><%= @today_book.count %></td>
          <td><%= @today_book.count - @oneday_ago_book.count %>
            <!--% if @oneday_ago_book.count == 0 %-->
              <!--前日の投稿が0のため計算できません-->
            <!--% else %>
              <!--% @the_day_before =   @today_book.count / @oneday_ago_book.count.to_f  %-->
              <!--%= (@the_day_before * 100).round %>%-->
            <!--% end %-->
          </td>
        </tbody>
      </tr>
    </table>
  
    <table class='table table-hover table-inverse'>
      <tr>
        <thead>
          <th>先週</th>
          <th>今週</th>
          <th>先週比</th>
        </thead>
      </tr>
      <tr>
        <tbody>
          <td><%= @last_week_book.count %></td>
          <td><%= @week_book.count %></td>
          <td><%= @week_book.count - @last_week_book.count %>
            <!--% if @lastweek_book.count == 0 %-->
              <!--前週の投稿が0のため計算できません-->
            <!--% else %-->
              <!--% @the_week_before = @week_book.count / @last_week_book.count.to_f  %-->
            <!--%= (@the_week_before * 100).round %>%-->
            <!--% end %-->
          </td>
        </tbody>
      </tr>
    </table>
  
    <table class='table table-hover table-inverse'>
      <tr>
        <thead>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </thead>
      </tr>
      <tr>
        <tbody>
          <td><%= @sixday_ago_book.count %></td>
          <td><%= @fiveday_ago_book.count %></td>
          <td><%= @fourday_ago_book.count %></td>
          <td><%= @threeday_ago_book.count %></td>
          <td><%= @twoday_ago_book.count %></td>
          <td><%= @oneday_ago_book.count %></td>
          <td><%= @today_book.count %></td>
        </tbody>
      </tr>
    </table>
    
    <!--<script src="graph.js"></script>-->
    <!--Chart.jsでグラフ化-->
    <div>
      <canvas id="myLineChart", class="width: 100%"></canvas>
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      <script>
        $(document).on('turbolinks:load', function() {    //turbolinkの設定変更(documentはだめだった、windowでいけた)
        //   document.write("<p>JavaScript テスト</p>");
        // });
      // /script>
          let ctx = document.getElementById("myLineChart");    //A.グラフを表示するという関数を定義(id)
          //ctxとは "canvas context" の略で、canvas要素の描画コンテキストを指している
          let myLineChart = new Chart(ctx, {     //B.グラフの内容を決める関数を定義している
            type: 'line',
            data: {
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],    //横軸ラベル
              datasets: [{
                label: '投稿した本の数',    //系列名
                data: [    //x軸データ
                  <%= @sixday_ago_book.count %>,
                  <%= @fiveday_ago_book.count %>,
                  <%= @fourday_ago_book.count %>,
                  <%= @threeday_ago_book.count %>,
                  <%= @twoday_ago_book.count %>,
                  <%= @oneday_ago_book.count %>,
                  <%= @today_book.count %>
                ],
                borderColor: "#000080",    //線の色
                tension: 0.2    //線の曲線度合い
              }]
            },
            options: {
              title: {    //グラフタイトル
                display: true,    //表示するか否か
                text: '直近7日間の投稿数推移'    //文面
              },
              responsive: true,    //画面サイズ変更に伴ってグラフのサイズ変更するか否か
              backgroundColor: "#f000000",    //背景色
              scales: {    //軸に対する設定
                y:{    //y軸に対する設定
                  min: 0,    //y軸の最小値
                  max: 10    //y軸の最大値
                },
                x: {    //x軸に対する設定
                }
              }
            }
          });
        });
      </script>
    </div>

app/views/users/_date.html.erb
  <div>

    <table>
      <th>投稿数</th>
      <td><%= date_book.count %></td>
    </table>
    
  </div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= "フォロー数:#{user.followeds.count}"%></td>
        <td><%= "フォロワー数:#{user.followers.count}"%></td>
        <td>
          <% unless user == current_user %>
            <% if current_user.followed?(user) %>
              <%= link_to user_relationships_path(user),method: :delete do%>
              フォロー外す
              <% end %>
            <% else %>
              <%= link_to user_relationships_path(user),method: :post do%>
                フォローする
              <% end %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followeds_path(user),method: :get do %>
        <%= user.followeds.count%>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_followers_path(user),method: :get do %>
        <%= user.followers.count%>
      <% end %>
    </th>
  </tr>
  <tr class="table table-borderless">
    <th>
      <% unless user == current_user %>
        <% if current_user.followed?(user) %>
          <%= link_to user_relationships_path(user), class: "btn btn-info",method: :delete do%>
          フォロー外す
          <% end %>
        <% else %>
          <%= link_to user_relationships_path(user), class: "btn btn-success",method: :post do%>
            フォローする
          <% end %>
        <% end %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/date_count.js.erb
<!--非同期通信の動作用-->
$('#date_book').html("<%= escape_javascript(render partial: 'users/date',locals: {date_book: @date_book}) %>");

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<body>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'info', user: current_user %>
        
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <%= render 'index',users: @users %>
        
        
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'info', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <%= render 'books/index',books: @books %>
        
        <!--日付指定で検索し、投稿数を非同期通信で表示-->
        <h5>日付指定で検索</h5>
        <%= form_with url: user_date_count_path(@user), method: :get, local: false do|f| %>
          <%= f.date_field :created_at %>
          <%= f.submit "検索", class: "btn btn-primary"%>
        <% end %>
        <div id="date_book"></div>
        
        <!--投稿数のデータ-->
        <%= render 'books_data',books: @books %>
      </div>
    </div>
  </div>